- hosts: localhost
  vars:
    username: jens
  become: true

  tasks:
#    - include: tasks/users.yml
#    - include: tasks/sw_settings.yml
#    - include: tasks/sw_packages.yml
#    - include: tasks/w_packages.yml
#    - include: tasks/w_cron.yml
#    - include: tasks/w_gnome.yml
#    - include: tasks/sw_oh-my-zsh.yml
#    - include: tasks/w_settings.yml
    - include: tasks/w_config-files-st.yml
