- hosts: localhost
  vars:
#    username: jens
  become: true
  pre_tasks:
    - name: update repositories (Ubuntu)
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_facts['ansible_distribution'] == 'Ubuntu'

  tasks:
    - include: tasks/users.yml
    - include: tasks/sw_settings.yml
    - include: tasks/sw_packages.yml
    - include: tasks/w_packages.yml
    - include: tasks/w_cron.yml
#    - include: tasks/w_gnome.yml
    - include: tasks/sw_oh-my-zsh.yml
    - include: tasks/w_settings.yml
    - include: tasks/w_kde.yml
    - include: tasks/w_config-files-st.yml
    - include: tasks/w_networkshares.yml
