- hosts: localhost
#  vars:
#     username: ansible_user_id
  #become: true
  pre_tasks:
    - name: update repositories (Ubuntu)
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username
    - name: get the home directory of the user, running the deploy
      become: false
      local_action: command echo ~"{{ username.stdout }}"
      register: userdir
    - name: Debug (display username)
      debug: var=username.stdout
    - name: Debug (display user's home directory)
      debug: var={{ userdir }}
    - include_tasks: tasks/users.yml
      when: ansible_distribution == 'Ubuntu'
    - include_tasks: tasks/ubuntu_settings.yml
      when: ansible_distribution == 'Ubuntu'
#    - include_tasks: tasks/ubuntu_packages.yml
#      when: ansible_distribution == 'Ubuntu'

    - include_tasks: tasks/ubuntu_cron.yml
      when: ansible_distribution == 'Ubuntu'
    - include_tasks: tasks/ubuntu_oh-my-zsh.yml
      vars:
        uname: "{{ ansible_user_id }}"
        udir: "{{ ansible_user_dir }}"
    - include_tasks: tasks/ubuntu_oh-my-zsh.yml
      vars:
        uname: root
        udir: /root
#    - include: tasks/w_kde.yml
#    - include: tasks/w_config-files-st.yml
#    - include: tasks/w_networkshares.yml
