- hosts: localhost
  vars:
    username: ansible_facts['ansible_user_id']
  become: true
  pre_tasks:
    - name: update repositories (Ubuntu)
      apt:
        update_cache: yes
        allow_unauthenticated: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

  tasks:
    - include: tasks/users.yml
      when: ansible_distribution == 'Ubuntu'
    - include: tasks/ubuntu_settings.yml
      when: ansible_distribution == 'Ubuntu'
    - include: tasks/ubuntu_packages.yml
      when: ansible_distribution == 'Ubuntu'

#    - include: tasks/w_cron.yml
#    - include: tasks/sw_oh-my-zsh.yml
#    - include: tasks/w_kde.yml
#    - include: tasks/w_config-files-st.yml
#    - include: tasks/w_networkshares.yml
