- hosts: localhost
  vars:
    username: jens
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache=yes
        changed_when: False
        allow_unauthenticated: yes

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron_workstation.yml
    - include: tasks/oh-my-zsh.yml
