- name: install cron job (ansible-pull)
  cron: user="ansible" name="ansible provision" minute="*/10" job="sudo /usr/bin/ansible-pull -U https://github.com/WolfgrammJ/ansible-pull.git kali.yml > /dev/null"

#- name: install cron job (backup-home-dir)
#  cron: user="{{ username }}" name="backup home dir" minute="0" hour="17" job="sh /home/{{ username }}/backup-home-dir.sh > /dev/null"
