- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower}}.yml"
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_os_family|lower }}.yml"

###############################################################
# Syncthing preparation for Debian
###############################################################

- name: Add PGP key and repository for syncthing
  become: yes
  raw: |
    curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
    echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
  when: ansible_facts['os_family'] == 'Debian'


###############################################################
# Update repositories after adding repos (Debian/Suse)
###############################################################

- name: Update repositories cache (Debian)
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'


###############################################################
# Install packages from repos
###############################################################

- name: Install workstation packages (all Ditros)
  ansible.builtin.package:
    name:
      - remmina
      - syncthing
#      - "{{ java }}"
      - "{{ freerdp }}"
      - terminator 
      - cifs-utils
#      - "{{ smbclient }}"
      - dolphin
      - dolphin-plugins
      - kwrite
#      - snapd
    state: latest

- name: Install workstation packages (Debian)
  ansible.builtin.package:
    name:
      - remmina-plugin-exec
      - remmina-plugin-www
#      - remmina-plugin-nx
      - remmina-plugin-kwallet
      - autofs
    state: latest
  when: ansible_facts['os_family'] == 'Debian'


###############################################################
# Install additional software
###############################################################

### TeamViewer (Debian)
- name: Install TeamViewer (Debian)
  become: yes
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: ansible_facts['os_family'] == 'Debian'


### NetExtender
- name: Download NetExtender version 10.2.824
  become_user: "{{ username }}"
  get_url:
    url: https://software.sonicwall.com/NetExtender/NetExtender.Linux-10.2.824.x86_64.tgz
    dest: /home/{{ username }}/NetExtender.Linux.tgz
  when: not netextender.stat.exists

- name: Extract NetExtender archive
  become_user: "{{ username }}"
  ansible.builtin.unarchive:
    src: /home/{{ username }}/NetExtender.Linux.tgz
    dest: /home/{{ username }}/
  when: not netextender.stat.exists

- name: Install NetExtender
  become: yes
  shell: ./install
  args:
    chdir: /home/{{ username }}/netExtenderClient/
    creates: /usr/bin/netExtenderGui
  when: not netextender.stat.exists

- name: Delete Netextender installation files
  become: yes
  ansible.builtin.file:
    path: /home/{{ username }}/NetExtender.Linux.tgz
    state: absent

- name: Set NetExtender Permissions 1
  ansible.builtin.file:
    path: /usr/sbin/pppd
    state: file
    mode: '4755'

- name: Set NetExtender Permissions 2
  ansible.builtin.file:
    path: /etc/ppp/peers
    state: directory
    mode: '2755'

- name: Set NetExtender Permissions 3 (Debian)
  ansible.builtin.file:
    path: /etc/ppp/peers/provider
    state: file
    mode: '0644'
  when: ansible_facts['os_family'] == 'Debian'

- name: Set NetExtender Permissions4
  ansible.builtin.file:
    path: /etc/ppp/peers
    state: directory
    mode: '2755'

- name: Remove NetExtender directory
  ansible.builtin.file:
    path: /home/{{ username }}/netExtenderClient/
    state: absent

- name: Download and move syncthing service
  become_user: "{{ username }}"
  raw: |
    wget -P ~/ https://raw.githubusercontent.com/syncthing/syncthing/main/etc/linux-systemd/system/syncthing%40.service
    sudo chown root: syncthing@.service
    sudo mv ~/syncthing@.service /etc/systemd/system

- name: Setting up syncthing service
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: syncthing@"{{ username }}"
  ignore_errors: yes

- name: Start syncthing service explicitly
  become: yes
  ansible.builtin.systemd:
    state: started
    name: syncthing@"{{ username }}"
  ignore_errors: yes

