- name: make zsh default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: Install Oh-my-zsh
  become_user: "{{ username }}"
  raw: sh $(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)
  executable: /usr/bin/sh
  args:
    warn: no
