- name: make zsh default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: Check if directory "~/.oh-my-zsh" exists
  stat:
    path: /home/{{ username }}/.oh-my-zsh
  register: omz

- name: Download install-script for oh-my-zsh
  become_user: "{{ username }}"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/install-oh-my-zsh.sh
    mode: '0777'
  when: not omz.stat.exists and not omz.stat.isdir

- name: Install Oh-my-zsh
  become_user: "{{ username }}"
  shell: ~/install-oh-my-zsh.sh
  when: not omz.stat.exists and not omz.stat.isdir

- name: Delete install-script for oh-my-zsh
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: ~/install-oh-my-zsh.sh
    state: absent

- name: Clone git repo "zsh-autosuggestions"
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Clone git repo "zsh-syntax-highlighting"
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Install requirements for autojump
  apt:
    pkg:
    - python
    - python3
    state: present

- name: Clone git repo "autojump"
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: http://github.com/wting/autojump.git
    dest: ~/autojump

- name: Install autojump
  become_user: "{{ username }}"
  script: /home/{{ username }}/autojump/install.py
  args:
    chdir: /home/{{ username }}/autojump

- name: Delete autojump installation directory
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: ~/autojump
    state: absent

- name: Add autojump to .zshrc
  become_user: "{{ username }}"
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: "^\[\[ -s /home/{{ username }}/.autojump"
    line: test
#    line: '[[ -s /home/jens/.autojump/etc/profile.d/autojump.sh ]] && source /home/jens/.autojump/etc/profile.d/autojump.sh'
