- name: make zsh default shell
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"

- name: Check if directory "~/.oh-my-zsh" exists
  become_user: "{{ username }}"
  stat:
    path: ~/.oh-my-zsh
  register: omz
  when: omz.stat.isdir is defined and omz.stat.isdir

- name: Download install-script for oh-my-zsh
  become_user: "{{ username }}"
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/install-oh-my-zsh.sh

- name: Install Oh-my-zsh
  become_user: "{{ username }}"
  shell: ~/install-oh-my-zsh.sh
#  when: not omz.stat.exists
