- name: Install packages
  ansible.builtin.package:
    name:
      - htop
      - mc
      - neofetch
      - tmux
      - zsh
      - remmina
      - snapd
    state: latest

- name: Configure tmux local
  ansible.builtin.copy:
    src: files/.tmux.conf
    dest: /home/{{ username }}/.tmux.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: yes

- name: Configure tmux remote
  ansible.builtin.copy:
    src: files/.tmux.remote.conf
    dest: /home/{{ username }}/.tmux.remote.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: yes

- name: Clone tmux plugin-manager git-repository
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Copy backup-home-dir.sh
  ansible.builtin.copy:
    src: files/backup-home-dir.sh
    dest: /home/{{ username }}/backup-home-dir.sh
    owner: "{{ username }}"
    group: "{{ username }}"
    backup: yes

- name: Install tmux-plugins
  become_user: "{{ username }}"
  raw: |
    tmux new -d -s __noop >/dev/null 2>&1 || true 
    tmux set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins"
    "$HOME"/.tmux/plugins/tpm/bin/install_plugins || true
    tmux kill-session -t __noop >/dev/null 2>&1 || true

