- name: Check if directory "~/.config-files-st" exists
  become_user: "{{ username }}"
  stat:
    path: ~/.config-files-st
  register: configfilesst

- name: Delete Terminator config file
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: ~/.config/terminator/config
    state: absent
  when: configfilesst.stat.exists

- name: Add symlink for terminator config
  become_user: "{{ username }}"
  ansible.builtin.file:
    src: ~/.config/terminator/config
    dest: ~/.config-files-st/terminator
    state: link
  when: configfilesst.stat.exists
