- name: Check if directory "~/.config-files-st" exists
  become_user: "{{ username }}"
  stat:
    path: ~/.config-files-st
  register: configfilesst

- name: Create directory "~/.config/terminator" if it does not exist
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: ~/.config/terminator
    state: directory
  when: configfilesst.stat.exists

- name: Add symlink for Terminator config
  become_user: "{{ username }}"
  ansible.builtin.file:
    src: ~/.config-files-st/terminator
    dest: ~/.config/terminator/config
    state: link
    force: yes
  when: configfilesst.stat.exists

- name: Create directory "~/.local/share/remmina" if it does not exist
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: ~/.local/share/remmina
    state: directory
  when: configfilesst.stat.exists

- name: Add symlink for Remmina
  become_user: "{{ username }}"
  ansible.builtin.file:
    src: ~/.config-files-st/remmina/
    dest: ~/.local/share/remmina
    state: link
    force: yes
  when: configfilesst.stat.exists

- name: Add symlink for KDE shortcuts (1)
  become_user: "{{ username }}"
  ansible.builtin.file:
    src: ~/.config-files-st/KDE/kglobalshortcutsrc
    dest: ~/.config/kglobalshortcutsrc
    state: link
    force: yes
  when: configfilesst.stat.exists

- name: Add symlink for KDE shortcuts (2)
  become_user: "{{ username }}"
  ansible.builtin.file:
    src: ~/.config-files-st/KDE/khotkeysrc
    dest: ~/.config/khotkeysrc
    state: link
    force: yes
  when: configfilesst.stat.exists
