- name: Clone git repo "virtual-desktop-bar"
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/wsdfhjxc/virtual-desktop-bar.git
    dest: ~/virtual-desktop-bar

- name: Install/update virtual-desktop-bar dependencies
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.shell: install-dependencies-ubuntu.sh
    args:
      chdir: /home/{{ username }}/virtual-desktop-bar/scripts/
  when: ansible_facts['os_family'] == 'Debian'

