- name: Clone git repo "virtual-desktop-bar"
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/wsdfhjxc/virtual-desktop-bar.git
    dest: ~/virtual-desktop-bar

- name: Install/update virtual-desktop-bar dependencies (Fedora)
  become: yes
  shell: yes | sh /home/{{ username }}/virtual-desktop-bar/scripts/install-dependencies-fedora.sh
  when: ansible_distribution == 'Fedora'

- name: Install/update virtual-desktop-bar dependencies (Debian)
  become: yes
  shell: yes | sh /home/{{ username }}/virtual-desktop-bar/scripts/install-dependencies-ubuntu.sh
  when: ansible_facts['os_family'] == 'Debian'

- name: Install/update virtual-desktop-bar dependencies (Arch)
  become: yes
  shell: yes | sh /home/{{ username }}/virtual-desktop-bar/scripts/install-dependencies-arch.sh
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Install/update virtual-desktop-bar dependencies (Suse)
  become: yes
  shell: yes | sh /home/{{ username }}/virtual-desktop-bar/scripts/install-dependencies-opensuse.sh
  when: ansible_facts['os_family'] == 'Suse'

- name: Install/update virtual-desktop-bar
  become_user: "{{ username }}"
  shell: ./install-applet.sh
  args:
    chdir: ~/virtual-desktop-bar/scripts/
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Archlinux' or ansible_facts['os_family'] == 'Suse' or ansible_distribution == 'Fedora'

# latte-dock (Redhat)
- name: Install latte-dock
  become: yes
  dnf:
    name: latte-dock
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

# RPM Fusion (Fedora)
- name: Install RPM Fusion (1/2)
  become: yes
  dnf:
    name: 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm'
    state: present
    disable_gpg_check: yes
  when: ansible_facts['os_family'] == 'RedHat' and ansible_distribution == 'Fedora'

- name: Install RPM Fusion (2/2)
  become: yes
  dnf:
    name: 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm'
    state: present
    disable_gpg_check: yes
  when: ansible_facts['os_family'] == 'RedHat' and ansible_distribution == 'Fedora'

# Kate (Fedora)
- name: Install Kate
  become: yes
  dnf:
    name: kate
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_distribution == 'Fedora'
