- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower}}.yml"
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_os_family|lower }}.yml"

- name: Install workstation packages
  ansible.builtin.package:
    name:
      - remmina
      - "{{ java }}"
      - "{{ freerdp }}"
      - terminator 
      - cifs-utils
    state: latest

- name: Install TeamViewer (Debian)
  become: yes
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: ansible_facts['os_family'] == 'Debian'

- name: Install TeamViewer (RedHat)
  become: yes
  dnf:
    name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Check if NetExtender is installed
  stat:
    path: /usr/bin/netExtenderGui
  register: netextender

- name: Download NetExtender version 10.2.824
  become_user: "{{ username }}"
  get_url:
    url: https://software.sonicwall.com/NetExtender/NetExtender.Linux-10.2.824.x86_64.tgz
    dest: /home/{{ username }}/NetExtender.Linux.tgz
  when: not netextender.stat.exists

- name: Extract NetExtender archive
  become_user: "{{ username }}"
  ansible.builtin.unarchive:
    src: /home/{{ username }}/NetExtender.Linux.tgz
    dest: /home/{{ username }}/
  when: not netextender.stat.exists

- name: Install NetExtender
  become: yes
  shell: ./install
  args:
    chdir: /home/{{ username }}/netExtenderClient/
    creates: /usr/bin/netExtenderGui
  when: not netextender.stat.exists

- name: Set NetExtender Permissions 1
  ansible.builtin.file:
    path: /usr/sbin/pppd
    state: file
    mode: '4755'

- name: Set NetExtender Permissions 2
  ansible.builtin.file:
    path: /etc/ppp/peers
    state: directory
    mode: '2754'

- name: Set NetExtender Permissions 3
  ansible.builtin.file:
    path: /etc/ppp/peers/provider
    state: file
    mode: '0644'

- name: Set NetExtender Permissions4
  ansible.builtin.file:
    path: /etc/ppp/peers
    state: directory
    mode: '2755'

- name: Remove NetExtender directory
  ansible.builtin.file:
    path: /home/{{ username }}/netExtenderClient/
    state: absent

- name: Configure autofs "auto.master"
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    regex: '^/mnt/damantec '
    line: /mnt/damantec /etc/auto.damantec -timeout=0 --ghost

- name: Copy file auto.damantec for autofs
  become: yes
  ansible.builtin.copy:
    src: files/autofs/auto.damantec
    dest: /etc/auto.damantec

