- name: Install workstation packages
  apt:
    pkg:
    - remmina
    - default-jre
    - arc-theme

- name: Install TeamViewer
  become: yes
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

- name: Check if NetExtender is installed
  stat:
    path: /usr/bin/netExtenderGui
  register: netextender

- name: Download NetExtender version 10.2.824
  become_user: "{{ username }}"
  get_url:
    url: https://software.sonicwall.com/NetExtender/NetExtender.Linux-10.2.824.x86_64.tgz
    dest: /home/{{ username }}/NetExtender.Linux.tgz
  when: not netextender.stat.exists

- name: Extract NetExtender archive
  become_user: "{{ username }}"
  ansible.builtin.unarchive:
    src: /home/{{ username }}/NetExtender.Linux.tgz
    dest: /home/{{ username }}/
  when: not netextender.stat.exists

- name: Install NetExtender
  become: yes
  shell: ./install
  args:
    chdir: /home/{{ username }}/netExtenderClient/
    creates: /usr/bin/netExtenderGui
  when: not netextender.stat.exists

- name: Remove NetExtender directory
  ansible.builtin.file:
    path: /home/{{ username }}/netExtenderClient/
    state: absent

- name: Check if VMware Workstation Pro is installed
  stat:
    path: /usr/bin/vmware
  register: vmware

- name: Download VMware Workstation Pro
  become_user: "{{ username }}"
  get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: /home/{{ username }}/VMware_Workstation_Pro.bundle
  when: not vmware.stat.exists
  
- name: Install VMware Workstation Pro
  become: yes
  ansible.builtin.command: ./home/{{ username }}/VMware_Workstation_Pro.bundle
