- name: Copy ".aliases_workstaion"
  ansible.builtin.copy:
    src: files/.aliases_workstation
    dest: /home/{{ username }}/.aliases
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '744'
    backup: yes

- name: Adding ".aliases" file to ".zshrc"
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.zshrc
    line: source ~/.aliases
    state: present
